name: mobile
description: "Mobile-specific code for the project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  # Dependency Injection
  get_it: ^7.7.0

  # Connectivity
  internet_connection_checker_plus: ^2.5.0

  # Cached Image
  cached_network_image: ^3.3.1

  # Video Player
  youtube_player_flutter: 9.0.0 # Version 9.0.1 has a bug

  # State Management
  flutter_bloc: ^8.1.4
  provider: ^6.1.2

  # Core Utility
  hive: ^2.2.3 # Local Database manager
  path: ^1.9.0 # File path utilities
  path_provider: ^2.1.3 # File path utilities

  # Localization and Internationalization
  localization: ^2.1.1
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/splash/

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Development Tools
  flutter_launcher_icons: ^0.13.1 # Create and generate the launcher icons
  flutter_lints: ^3.0.0 # Contains a recommended set of lints

flutter_launcher_icons:
  android: true
  remove_alpha_ios: true
  image_path: "lib/assets/splash/app_icon_rect.png"
  adaptive_icon_background: "lib/assets/splash/app_icon_background.png"
  adaptive_icon_foreground: "lib/assets/splash/app_icon_foreground.png"
