name: core
description: Core logic and business rules for the project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.4
  dio: ^5.5.0+1
  fpdart: ^1.1.0
  hive: ^2.2.3
  intl: ^0.19.0
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4

flutter:
  assets:
    - lib/assets/fonts/

  fonts:
    - family: Helvetica
      fonts:
        - asset: lib/assets/fonts/Helvetica-Bold.ttf
        - asset: lib/assets/fonts/Helvetica-Regular.ttf
